default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: praktykant
  password:

development:
  <<: *default
  database: blog_development

test:
  <<: *default
  database: blog_test